name: Action test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-job:
    # runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
      - name: 🔍 Checkout repository
        uses: actions/checkout@v6
        with:
          path: 'source_repo'
          fetch-depth: 1
          
      # - name: 🐍 Setup python
      #   uses: actions/setup-python@v6
      #   with:
      #     python-version: "3.14"

      # - name: 📌 Run test
      #   run: |
      #     cd source_repo 

      - name: 💾 Cache output
        uses: actions/cache@v6
        with:
          path: source_repo/test_manifest/output
          key: stellasora-manifest-${{ github.run_id }}
          restore-keys: stellasora-manifest-

      - name: 📌 Run test
        working-directory: source_repo/test_manifest
        run: |
          ./ManifestTool.exe
        shell: pwsh

      - name: 📤 Commit config.toml only
        working-directory: source_repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add test_manifest/config.toml
          git diff --staged --quiet || (git commit -m "Update config.toml [skip ci]" && git push)
        shell: pwsh
        